# Workflow name
name: Deploy to Heroku

# Trigger workflow on push to main branch
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Checkout
        uses: actions/checkout@v2

      # Log in to Heroku CLI to set the stack
      - name: Set Heroku stack to container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku stack:set container -a ${{ secrets.HEROKU_APP_NAME }}

      # Build, Push, and Release Docker container to Heroku
      - name: Deploy to Heroku via Docker
        uses: gonuit/heroku-
